# Generated by Django 2.1 on 2019-07-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
