# Generated by Django 2.1 on 2019-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20190716_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=350)),
                ('what', models.CharField(max_length=350)),
                ('where', models.CharField(max_length=350)),
                ('why', models.CharField(max_length=350)),
            ],
        ),
    ]
